version: '3.1'

services:
  bestiller-api:
    build:
      context: "."
      args:
        APPNAME: hops-bestiller-backend
    ports:
     - 8002:2022
    environment:
      - APP_INGRESS=http://localhost:8002
      - DB_HOST=pg
    env_file:
      - .env
    depends_on:
      - "mock-oauth2-server"
      - "pg"
  sof-questionnaire:
    build:
      context: "."
      args:
        APPNAME: sof-questionnaire
    ports:
      - 8003:2022
  bestiller-gui:
    build:
      context: "."
      args:
        APPNAME: hops-bestiller-frontend
    ports:
      - 8004:2022
  mock-oauth2-server:
    image: docker.pkg.github.com/navikt/mock-oauth2-server/mock-oauth2-server:0.3.1
    ports:
      - 8030:8030
    environment:
      - SERVER_PORT=8030
    hostname: host.docker.internal
  pg:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    command: -p ${DB_PORT}
