version: '3.1'

services:
  hops-bestiller-backend:
    build:
      context: "."
      args:
        app: hops-bestiller-backend
    ports:
     - 8002:2022
    environment:
      - port=2022
  sof-questionnaire:
    build:
      context: "."
      args:
        app: sof-questionnaire
    ports:
      - 8003:2022
    environment:
      - port=2022
