apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-bestiller-backend
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  image: {{ image }}
  port: 2022
  team: helseopplysninger
  liveness:
    path: /internal/is-alive
  readiness:
    path: /internal/is-ready
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 128Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: /internal/prometheus
  ingresses:
    - {{ingress}}
  env:
    - name: APP_INGRESS
      value: {{ingress}}
