name: default

on:
  push:
    branches:
      - "*"

env:
  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
  NX_BASE: ""

jobs:
  test:
    name: Test and build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch origin main
      - run: |
          if [[ ${{ github.ref == 'refs/heads/main' }} == true ]]; then
            echo "NX_BASE=~1" >> $GITHUB_ENV
          fi
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci --no-audit --prefer-offline --no-optional --ignore-scripts
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"appname\":$(npm run matrix --silent)}"
      - run: npm run affected:test
      - run: npm run affected:build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 1

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix: ${{fromJSON(needs.test.outputs.matrix)}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - id: create-tag
        run: echo '::set-output name=SHORTSHA::'$(git rev-parse --short HEAD)
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: echo "deploying ${{ matrix.appname }}"
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06 # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_PUSH_USERNAME }}
          password: ${{ secrets.GHCR_PUSH_TOKEN }}
      - name: Build and tag docker image
        run: |
          TAG=${{ steps.create-tag.outputs.SHORTSHA }}
          IMAGE_BASE=ghcr.io/navikt/${{ matrix.appname }}
          docker build --pull --tag ${IMAGE_BASE}:${TAG} --tag ${IMAGE_BASE}:latest --build-arg APPNAME=${{ matrix.appname }} .
      - name: Push docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push ${IMAGE_BASE}:latest
          docker push ${IMAGE_BASE}:${TAG}
      - name: Deploy to Dev
        uses: nais/deploy/actions/deploy@master
        env:
          IMAGE: ghcr.io/navikt/${{ matrix.appname }}:${{ steps.create-tag.outputs.SHORTSHA }}
          CLUSTER: dev-gcp
          DRY_RUN: ${{ github.ref != 'refs/heads/main' }}
          VAR: ingress=https://${{ matrix.appname }}.dev.nav.no
          RESOURCE:  apps/${{ matrix.appname }}/naiserator.yaml




